technologies = {
    "API",
    "APIs",
    "HTML5",
    "CSS3",
    "JavaScript",
    "TypeScript",
    "React",
    "Angular",
    "Vue.js",
    "Bootstrap",
    "Sass",
    "Less",
    "Tailwind CSS",
    "jQuery",
    "Redux",
    "GraphQL",
    "Next.js",
    "Gatsby",
    "Webpack",
    "Babel",
    "ESLint",
    "Prettier",
    "Responsive Design",
    "Progressive Web Apps",
    "RESTful APIs",
    "JSON",
    "XML",
    "Axios",
    "Fetch API",
    "WebSocket",
    "Service Workers",
    "WebAssembly",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Spring Boot",
    "ASP.NET Core",
    "Laravel",
    "Symfony",
    "Ruby",
    "Python",
    "Java",
    "C#",
    "PHP",
    "Go",
    "Scala",
    "Kotlin",
    "Rust",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Redis",
    "Elasticsearch",
    "GraphQL",
    "RESTful APIs",
    "JSON",
    "XML",
    "Docker",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "Elasticsearch" ,
    "Logstash",
    "Kibana"
    "Jaeger",
    "Zipkin",
    "Amazon Web Services",
    "Google Cloud Platform",
    "Azure",
    "Istio",
    "Envoy",
    "Nagios",
    "Zabbix",
    "New Relic",
    "Datadog",
    "Splunk",
    "Consul",
    "Vault",
    "Jenkins",
    "Spinnaker",
    "GitLab CI/CD",
    "GitHub Actions",
    "PagerDuty",
    "OpsGenie",
    "Sentry",
    "HAProxy",
    "NGINX",
    "Apache Hadoop",
    "Apache Spark",
    "Apache Kafka",
    "Apache Flink",
    "Apache Beam",
    "Apache Cassandra",
    "Apache HBase",
    "Apache Hive",
    "Apache Airflow",
    "Apache NiFi",
    "Apache Storm",
    "Amazon S3",
    "Google BigQuery",
    "AWS",
    "GCP",
    "Microsoft Azure Data Lake",
    "Snowflake",
    "Databricks",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "SQL",
    "NoSQL",
    "ETL",
    "Data Warehousing",
    "Data Lakes",
    "Data Modeling",
    "Data Pipelines",
    "Streaming Data Processing",
    "Python",
    "R",
    "SQL",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Jupyter Notebooks",
    "RStudio",
    "Tableau",
    "Power BI",
    "Google Data Studio",
    "Excel",
    "Apache Spark",
    "SQL Server",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Data Cleaning",
    "Data Visualization",
    "Data Wrangling",
    "Statistical Analysis",
    "Machine Learning",
    "Time Series Analysis",
    "Natural Language Processing",
    "NLP",
    "Big Data Analytics",
    "Python",
    "R",
    "SQL",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Jupyter Notebooks",
    "RStudio",
    "Tableau",
    "Power BI",
    "Google Data Studio",
    "Excel",
    "Apache Spark",
    "Hadoop",
    "Hive",
    "Pig",
    "MapReduce",
    "SQL Server",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Data Cleaning",
    "Data Visualization",
    "Machine Learning",
    "Selenium",
    "Appium",
    "WebDriver",
    "TestNG",
    "JUnit",
    "JUnit Jupiter",
    "Cucumber",
    "Behave",
    "Robot Framework",
    "PyTest",
    "JUnit",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitLab CI/CD",
    "Sauce Labs",
    "BrowserStack",
    "Postman",
    "SoapUI",
    "JMeter",
    "LoadRunner",
    "Katalon Studio",
    "TestComplete",
    "TestRail",
    "Jira",
    "Bugzilla",
    "HP Quality Center",
    "Zephyr",
    "SpiraTest",
    "Xray Test Management",
    "Cisco IOS",
    "Juniper Junos",
    "Huawei VRP",
    "TCP/IP",
    "OSPF",
    "BGP",
    "MPLS",
    "VLAN",
    "STP",
    "VRRP",
    "HSRP",
    "GLBP ",
    "VPN",
    "Firewalls",
    "Load Balancers",
    "F5 BIG-IP",
    "Wireshark",
    "Packet Tracer",
    "GNS3",
    "Nmap",
    "Ping",
    "Traceroute",
    "NetFlow",
    "SNMP",
    "Syslog",
    "QoS",
    "IPv4",
    "IPv6",
    "DHCP",
    "DNS",
    "SSH",
    "Firewalls",
    "IDS",
    "IPS",
    "VPN",
    "SSL/TLS",
    "IPSec",
    "SNMP",
    "Syslog",
    "SIEM",
    "DLP",
    "WAF",
    "DDoS Protection",
    "Endpoint Security Solutions",
    "NAC",
    "Two-Factor Authentication",
    "Metasploit", 
    "Nmap",
    "Nessus",
    "OpenVAS",
    "Security Assessment Tools",
    "Network Security Policies",
    "Security Incident Response Plans",
    "Security Information Sharing Platforms",
    "Encryption",
    "Digital Certificates",
    "Security Hardening Techniques",
    "Security Patch Management",
    "IAM",
    "Zero Trust Security",
    "Container Security",
    "Cloud Security",
    "Mobile Device Management" ,
    "(MDM)"
}